### ISSUE TITLE
Migration tool throws SQL error in MySQL database with UTF8

### ISSUE THREAD

**Issue by mazurva** [bedezign/yii2-audit#122]
When I try to deploy your migration, the following error occurs (very similar to the [Issue 1204 in Yii2](https://github.com/yiisoft/yii2/issues/1204))

```
*** applying m150626_000003_create_audit_error
    > create table {{%audit_error}} ... done (time: 0.034s)
    > add foreign key fk_audit_error_entry_id: {{%audit_error}} (entry_id) references {{%audit_entry}} (id) ... done (time: 0.053s)
    > create index idx_file on {{%audit_error}} (file) ...An Error occurred while handling another error:
exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: yii\console\Response::isSent' in /var/www/vendor/yiisoft/yii2/base/Component.php:197
Stack trace:
#0 /var/www/vendor/yiisoft/yii2/web/ErrorHandler.php(74): yii\base\Component->__set('isSent', false)
#1 /var/www/vendor/yiisoft/yii2/base/ErrorHandler.php(109): yii\web\ErrorHandler->renderException(Object(yii\db\Exception))
#2 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\db\Exception))
#3 {main}
Previous exception:
exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes' in /var/www/vendor/yiisoft/yii2/db/Command.php:779
Stack trace:
#0 /var/www/vendor/yiisoft/yii2/db/Command.php(779): PDOStatement->execute()
#1 /var/www/vendor/yiisoft/yii2/db/Migration.php(422): yii\db\Command->execute()
#2 /var/www/vendor/bedezign/yii2-audit/src/migrations/m150626_000003_create_audit_error.php(28): yii\db\Migration->createIndex('idx_file', '{{%audit_error}...', Array)
#3 /var/www/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(492): m150626_000003_create_audit_error->up()
#4 /var/www/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(129): yii\console\controllers\BaseMigrateController->migrateUp('m150626_000003_...')
#5 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#6 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#7 /var/www/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#8 /var/www/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('', Array)
#9 /var/www/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('', Array)
#10 /var/www/vendor/yiisoft/yii2/console/Application.php(166): yii\base\Module->runAction('migrate', Array)
#11 /var/www/vendor/yiisoft/yii2/console/Application.php(142): yii\console\Application->runAction('migrate', Array)
#12 /var/www/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#13 /var/www/yii(31): yii\base\Application->run()
#14 {main}

Next exception 'yii\db\Exception' with message 'SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
The SQL being executed was: ALTER TABLE `audit_error` ADD INDEX `idx_file` (`file`)' in /var/www/vendor/yiisoft/yii2/db/Schema.php:615
Stack trace:
#0 /var/www/vendor/yiisoft/yii2/db/Command.php(789): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `au...')
#1 /var/www/vendor/yiisoft/yii2/db/Migration.php(422): yii\db\Command->execute()
#2 /var/www/vendor/bedezign/yii2-audit/src/migrations/m150626_000003_create_audit_error.php(28): yii\db\Migration->createIndex('idx_file', '{{%audit_error}...', Array)
#3 /var/www/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(492): m150626_000003_create_audit_error->up()
#4 /var/www/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(129): yii\console\controllers\BaseMigrateController->migrateUp('m150626_000003_...')
#5 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#6 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#7 /var/www/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#8 /var/www/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('', Array)
#9 /var/www/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('', Array)
#10 /var/www/vendor/yiisoft/yii2/console/Application.php(166): yii\base\Module->runAction('migrate', Array)
#11 /var/www/vendor/yiisoft/yii2/console/Application.php(142): yii\console\Application->runAction('migrate', Array)
#12 /var/www/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#13 /var/www/yii(31): yii\base\Application->run()
#14 {main}
Additional Information:
Array
(
    [0] => 42000
    [1] => 1071
    [2] => Specified key was too long; max key length is 767 bytes
)


```

**Comment by mazurva** [comment]
The problem is related to the field of `file`
I know of two solutions:
1. change the size of the field from 512 to 180
2. not create this key field in MySQL

**Comment by Blizzke** [comment]
I have those migrations deployed on at least 3 MySQL servers in a UTF-8 database and it has never failed. We are running continuous integration tests on SQLite, Postgres and MySQL that also run these migrations on every go and so far they haven't failed either. Are you perhaps running an older version of MySQL?

**Comment by mazurva** [comment]
MySQL v. 5.6

**Comment by Blizzke** [comment]
Weird. Anyhow, I'll see if we can limit the index site when on mysql.

**Comment by mazurva** [comment]
I'll try to test on other machines.

**Comment by cornernote** [comment]
this maybe of interest - http://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes

**Comment by cornernote** [comment]
```
SET @@global.innodb_large_prefix = 1;
```

**Comment by Blizzke** [comment]
For that one you need the `SUPER` permission, so not really the best solution, it's just adding another requirement. I'm simply going to modify the index size for mysql, it's not that important.

**Comment by Blizzke** [comment]
@mazurva Should work now. Please also note that (given your initial log) it seems that you have installed the web error handler for the console part of your application as well. I've updated the docs reflect that they should use a separate error handler.

**Comment by zainalawaludin** [comment]
hi i trying migration but found error Exception 'yii\base\InvalidConfigException' with message 'The configuration for the "controllerMap" component must contain a "class" element.'

**Comment by Blizzke** [comment]
Please do not just comment on a closed and unrelated issue. Open a new one and add more info (like a stack trace).
