### ISSUE TITLE
Command cleanup error

### ISSUE THREAD

**Issue by markmarco16** [bedezign/yii2-audit#213]
Hello!

On yii2-audit version  1.0.11 have next errors on comandline cleanup:

```bash
 php yii audit/cleanup --age=0

PHP Notice 'yii\base\ErrorException' with message 'Trying to get property of non-object'

in /var/www/citaspro/vendor/bedezign/yii2-audit/src/commands/AuditController.php:67

Stack trace:
#0 /var/www/citaspro/vendor/bedezign/yii2-audit/src/commands/AuditController.php(67): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/var/www/citasp...', 67, Array)
#1 [internal function]: bedezign\yii2\audit\commands\AuditController->actionCleanup()
#2 /var/www/citaspro/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /var/www/citaspro/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#4 /var/www/citaspro/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('cleanup', Array)
#5 /var/www/citaspro/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('cleanup', Array)
#6 /var/www/citaspro/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('audit/cleanup', Array)
#7 /var/www/citaspro/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('audit/cleanup', Array)
#8 /var/www/citaspro/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#9 /var/www/citaspro/yii(20): yii\base\Application->run()
#10 {main}
```

if try send panels to cleanup, have next errors:
```bash
php yii audit/cleanup --panels=audit/request,audit/db,audit/log,audit/profiling,audit/javascript,audit/error,audit/extra,audit/curl --age=0

Total 8 cleanups to be applied:
	DATA                      CLEANUP TO DATETIME
	---------------------------------------------
Exception 'Error' with message 'Call to a member function getPanel() on null'

in /var/www/citaspro/vendor/bedezign/yii2-audit/src/commands/AuditController.php:123

Stack trace:
#0 /var/www/citaspro/vendor/bedezign/yii2-audit/src/commands/AuditController.php(71): bedezign\yii2\audit\commands\AuditController->preCleanupSummary(NULL, NULL, Array, '0')
#1 [internal function]: bedezign\yii2\audit\commands\AuditController->actionCleanup()
#2 /var/www/citaspro/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /var/www/citaspro/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#4 /var/www/citaspro/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('cleanup', Array)
#5 /var/www/citaspro/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('cleanup', Array)
#6 /var/www/citaspro/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('audit/cleanup', Array)
#7 /var/www/citaspro/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('audit/cleanup', Array)
#8 /var/www/citaspro/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#9 /var/www/citaspro/yii(20): yii\base\Application->run()
#10 {main}
```

**Comment by markmarco16** [comment]
Opd is my error, i forget register audit module on console config!

Sorry!
