### ISSUE TITLE
compressData enabled doesn't work in SQL Server

### ISSUE THREAD

**Issue by JSila** [bedezign/yii2-audit#255]
Hi,

I'm using SQL Server as my database. If I set `compressData => true` there are no entries logged in `audit_data`. When I look into app log, I see this warning:

```
2018-11-14 07:42:42 [127.0.0.1][96][-][warning][yii\log\Dispatcher::dispatch] Unable to send log via bedezign\yii2\audit\LogTarget: Exception (Database Exception) 'yii\db\Exception' with message 'SQLSTATE[IMSSP]: An error occurred translating string for input param 1 to UCS-2: No mapping for the Unicode character exists in the target multi-byte code page.

The SQL being executed was: INSERT INTO [audit_data] ([entry_id], [type], [created], [data]) VALUES (11, 'audit/request', '2018-11-14 07:42:42', 'x��Yms�H�....�vI')' 

in C:\Work\php\vps\vendor\yiisoft\yii2\db\Schema.php:664

Stack trace:
#0 C:\Work\php\vendor\yiisoft\yii2\db\Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO [au...')
#1 C:\Work\php\vendor\yiisoft\yii2\db\Command.php(1075): yii\db\Command->internalExecute('INSERT INTO [au...')
#2 C:\Work\php\vendor\bedezign\yii2-audit\src\models\AuditEntry.php(127): yii\db\Command->execute()
#3 C:\Work\php\vendor\bedezign\yii2-audit\src\LogTarget.php(57): bedezign\yii2\audit\models\AuditEntry->addBatchData(Array, false)
#4 C:\Work\php\vendor\bedezign\yii2-audit\src\LogTarget.php(74): bedezign\yii2\audit\LogTarget->export()
#5 C:\Work\php\vendor\yiisoft\yii2\log\Dispatcher.php(189): bedezign\yii2\audit\LogTarget->collect(Array, true)
#6 C:\Work\php\vendor\yiisoft\yii2\log\Logger.php(177): yii\log\Dispatcher->dispatch(Array, true)
#7 [internal function]: yii\log\Logger->flush(true)
```

Any idea how to fix this would be appreciated. I also use this package in other project with mysql database and I have no problem there.

**Comment by Blizzke** [comment]
I'm afraid we can't really be of much help here as we don't have SQL server at our disposition to test against. Perhaps you can change the column data type manually to something that does support binary data?
