### ISSUE TITLE
Handle error on backend

### ISSUE THREAD

**Issue by juniorari** [bedezign/yii2-audit#276]
I put this on backend\common\main.php
```
'components' => [
        'errorHandler' => [
            'class' => '\bedezign\yii2\audit\components\web\ErrorHandler',
        ],
```

But when i force any error, this is what happening:

```
An Error occurred while handling another error:
Error: Call to undefined function bedezign\yii2\audit\components\bcadd() in /var/www/html/sfc/vendor/bedezign/yii2-audit/src/components/Helper.php:199
Stack trace:
#0 /var/www/html/sfc/vendor/bedezign/yii2-audit/src/panels/ErrorPanel.php(66): bedezign\yii2\audit\components\Helper::hash()
#1 /var/www/html/sfc/vendor/bedezign/yii2-audit/src/components/base/ErrorHandlerTrait.php(42): bedezign\yii2\audit\panels\ErrorPanel->log()
#2 /var/www/html/sfc/vendor/yiisoft/yii2/base/ErrorHandler.php(131): bedezign\yii2\audit\components\web\ErrorHandler->logException()
#3 [internal function]: yii\base\ErrorHandler->handleException()
#4 {main}
Previous exception:
yii\base\ErrorException: Division by zero in /var/www/html/sfc/backend/controllers/DeviceController.php:162
Stack trace: (...)
```

Any sugestion?

**Comment by Gcsilva** [comment]
Did you find some solution for this?

**Comment by cornernote** [comment]
Do you have bcmath extension installed into php?

**Comment by eluhr** [comment]
As @cornernote and the [composer.json](https://github.com/bedezign/yii2-audit/blob/master/composer.json#L31) indicate, the audit module requires the bc-math extension for hashing the data.

https://www.php.net/manual/en/bc.installation.php
